<a href="https://colab.research.google.com/github/yang200212/MSSP-6070/blob/main/PARTICIPATION_ACTIVITY_Week_6_Write_a_lamda_function_for_a_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
student = pd.read_csv("/content/drive/My Drive/MSSP 6070/Modules/Week_6/Student Performance Data.csv")

In [4]:
# take a look at 'student' dataset's variables
student.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [5]:
# write a lambda function that transforms 'gender' to a binary variable, with female=0 and male=1
student_transform = lambda df: df.assign(
    gender_new=df["gender"].apply(lambda x: 0 if x == "female" else 1)
)

student_new = student_transform(student)

In [6]:
# check output
student_new.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect,gender_new
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium,0
1,female,group C,some college,standard,69,90,88,247,completed,high,0
2,female,group B,master's degree,standard,90,95,93,278,none,high,0
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low,1
4,male,group C,some college,standard,76,78,75,229,none,high,1