<a href="https://colab.research.google.com/github/yang200212/MSSP-6070/blob/main/Week_5_Participation_Activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
import pandas as pd
facebook = pd.read_csv("/content/drive/My Drive/MSSP 6070/Modules/Week_5/fb.csv")
apple = pd.read_csv("/content/drive/My Drive/MSSP 6070/Modules/Week_5/aapl.csv")
amazon = pd.read_csv("/content/drive/My Drive/MSSP 6070/Modules/Week_5/amzn.csv")
netflix = pd.read_csv("/content/drive/My Drive/MSSP 6070/Modules/Week_5/nflx.csv")
google = pd.read_csv("/content/drive/My Drive/MSSP 6070/Modules/Week_5/goog.csv")

In [8]:
facebook.head()

         date    open    high       low   close    volume
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726

In [9]:
apple.head()

         date      open      high       low     close    volume
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766

In [10]:
amazon.head()

         date     open     high      low    close   volume
0  2018-01-02  1172.00  1190.00  1170.51  1189.01  2694494
1  2018-01-03  1188.30  1205.49  1188.30  1204.20  3108793
2  2018-01-04  1205.00  1215.87  1204.66  1209.59  3022089
3  2018-01-05  1217.51  1229.14  1210.00  1229.14  3544743
4  2018-01-08  1236.00  1253.08  1232.03  1246.87  4279475

In [11]:
netflix.head()

         date    open    high       low   close    volume
0  2018-01-02  196.10  201.65  195.4200  201.07  10966889
1  2018-01-03  202.05  206.21  201.5000  205.05   8591369
2  2018-01-04  206.20  207.05  204.0006  205.63   6029616
3  2018-01-05  207.25  210.02  205.5900  209.99   7033240
4  2018-01-08  210.02  212.50  208.4400  212.05   5580178

In [12]:
google.head()

         date     open     high      low    close   volume
0  2018-01-02  1048.34  1066.94  1045.23  1065.00  1237564
1  2018-01-03  1064.31  1086.29  1063.21  1082.48  1430170
2  2018-01-04  1088.00  1093.57  1084.00  1086.40  1004605
3  2018-01-05  1094.00  1104.25  1092.00  1102.23  1279123
4  2018-01-08  1102.23  1111.27  1101.62  1106.94  1047603

In [13]:
# add a column to each dataframe called 'ticker', indicating the ticker symbol it is for (Apple is AAPL)
facebook["ticker"] = "FB"
apple["ticker"] = "AAPL"
amazon["ticker"] = "AMZN"
netflix["ticker"] = "NFLX"
google["ticker"] = "GOOG"

In [17]:
# append each file together into a single dataframe 'faanf'
faanf = pd.concat(
    [facebook, apple, amazon, netflix, google],
    ignore_index=True
)

In [18]:
# save faanf into csv
faanf.to_csv("faanf.csv", index=False)

In [19]:
faanf.head()

         date    open    high       low   close    volume ticker
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903     FB
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563     FB
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896     FB
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535     FB
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726     FB

In [21]:
faanf = pd.read_csv("faanf.csv")
# use type conversion to change the 'date' column into a 'datetime' and the 'volume' column into integers
faanf["date"] = pd.to_datetime(faanf["date"])
faanf["volume"] = faanf["volume"].astype(int)

# sort by 'date' and 'ticker'
faanf = faanf.sort_values(by = ["date", "ticker"])

In [22]:
faanf.head()

           date       open       high        low      close    volume ticker
251  2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
502  2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
0    2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
1004 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
753  2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX

In [23]:
# Find the seven rows within the highest value for volume
faanf.nlargest(7, "volume")

          date      open      high       low     close     volume ticker
142 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
53  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
57  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
54  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
433 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
496 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
463 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [24]:
# Use the melt() method to make the 'date' and 'ticker' key identifiers
# Melt the remaining columns so that they are not separated
faanf_melted = faanf.melt(
    id_vars=["date", "ticker"]
)

faanf_melted.head()

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000