<a href="https://colab.research.google.com/github/yang200212/MSSP-6070/blob/main/Modules/Week_6/PARTICIPATION_ACTIVITY_Week_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import userdata
import os
import subprocess
from pathlib import Path

owner = "yang200212" # Replace with the GitHub repository owner
repository = "MSSP-6070" # Replace with the GitHub repository name
repo_url = f'https://github.com/{owner}/{repository}.git'
repo_path = Path('/content') / repository

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', repo_url])

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print("Changed directory to: {os.getcwd()}")

Changed directory to: {os.getcwd()}

In [3]:
import subprocess

subprocess.run(
    ['git', '-C', str(repo_path), 'pull', 'origin', 'main'],
    check=True
)

CompletedProcess(args=['git', '-C', '/content/MSSP-6070', 'pull', 'origin', 'main'], returncode=0)

In [4]:
import pandas as pd

# Define dataset path
DATA_PATH = repo_path / 'Modules' / 'Week_6' / 'Student Performance Data.csv'

# Check whether the file exists
if not DATA_PATH.exists():
    raise FileNotFoundError(
        f"Data file not found: {DATA_PATH}"
    )

# Load the CSV dataset
student = pd.read_csv(DATA_PATH, encoding='cp1252')

# Confirm successful loading
print("Data loaded successfully!")
print("Data shape:", student.shape)
display(student.head())

Data loaded successfully!
Data shape: (1000, 10)

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [5]:
# take a look at 'student' dataset's variables
student.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [6]:
# write a lambda function that transforms 'gender' to a binary variable, with female=0 and male=1
student_transform = lambda df: df.assign(
    gender_new=df["gender"].apply(lambda x: 0 if x == "female" else 1)
)

student_new = student_transform(student)

In [7]:
# check output
student_new.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect,gender_new
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium,0
1,female,group C,some college,standard,69,90,88,247,completed,high,0
2,female,group B,master's degree,standard,90,95,93,278,none,high,0
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low,1
4,male,group C,some college,standard,76,78,75,229,none,high,1